{   'application': False,
    'assets': {},
    'author': 'Marc Wimmer (marc@itewimmer.de)',
    'data': ['data/config.xml'],
    'demo': [],
    'depends': [],
    'external_dependencies': {'bin': [], 'python': []},
    'name': 'move_attachments_from_file_to_db',
    'pre_init_hook': 'pre_init_hook',
    'test': [],
    'version': '13.0.1.0'}
